pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: GitVersion@4
  inputs:
    updateAssemblyInfo: true

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration) -p:Version='

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    searchPatternPack: '**/Redis/NRedis.csproj'
    nobuild: true
    buildProperties: '-p:PackageVersion=$(GitVersion.NuGetVersion)'
    verbosityPack: 'Normal'

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'drop'