//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Caching.Redis.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Caching.Redis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be empty..
        /// </summary>
        internal static string ArgumentCannotBeEmpty {
            get {
                return ResourceManager.GetString("ArgumentCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed..
        /// </summary>
        internal static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot marshal &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string CannotMarshalFromTypeToType {
            get {
                return ResourceManager.GetString("CannotMarshalFromTypeToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read from Pipe. State if the reader, IsCanceled: &apos;{0}&apos;, IsCompleted: &apos;{1}&apos;..
        /// </summary>
        internal static string CannotReadFromPipe {
            get {
                return ResourceManager.GetString("CannotReadFromPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; not supported in conversion..
        /// </summary>
        internal static string FormatterTypeNotSupported {
            get {
                return ResourceManager.GetString("FormatterTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number format for &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidFormatOnType {
            get {
                return ResourceManager.GetString("InvalidFormatOnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count of responses (&apos;{0}&apos;) do not match with the count of requests (&apos;{1}&apos;)..
        /// </summary>
        internal static string InvalidResponsesCount {
            get {
                return ResourceManager.GetString("InvalidResponsesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character detected at the begin of the data, near position &apos;{0}&apos;..
        /// </summary>
        internal static string ProtocolViolationInvalidBeginChar {
            get {
                return ResourceManager.GetString("ProtocolViolationInvalidBeginChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character detected at the end of the data, near position &apos;{0}&apos;..
        /// </summary>
        internal static string ProtocolViolationInvalidEndChar {
            get {
                return ResourceManager.GetString("ProtocolViolationInvalidEndChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response has some not expected data at position &apos;{0}&apos;..
        /// </summary>
        internal static string ProtocolViolationNotExpectedData {
            get {
                return ResourceManager.GetString("ProtocolViolationNotExpectedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse Integer value, near position &apos;{0}&apos;..
        /// </summary>
        internal static string ProtocolViolationParsingInteger {
            get {
                return ResourceManager.GetString("ProtocolViolationParsingInteger", resourceCulture);
            }
        }
    }
}
